# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 637)
        MainWindow.setMaximumSize(QtCore.QSize(1220, 637))
        MainWindow.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 211, 631))
        self.label.setStyleSheet("background-color: rgb(227, 242, 253);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 181, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #E3F2FD; /* Very light blue shade */  \n"
"    color: rgb(14, 36, 51);\n"
"    border: none; /* No border */\n"
"    border-radius: 4px; /* Slightly rounded corners */\n"
"    padding: 10px 20px; /* Padding inside the button */\n"
"    font: 700 11pt \"Segoe UI\";\n"
"     /* Subtle shadow */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BBDEFB; /* Darker light blue shade on hover */\n"
"    color: rgb(14, 36, 51); /* Change text color on hover */\n"
"    border-right: 2px solid black; /* Make the right side thicker */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90CAF9; /* Even darker light blue when pressed */\n"
"   /* Remove shadow on press */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #E3F2FD; /* Very light blue background for disabled state */\n"
"    color: #BCAAA4; /* Light blue text for disabled state */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("house.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 30, 941, 561))
        self.widget.setMinimumSize(QtCore.QSize(941, 561))
        self.widget.setMaximumSize(QtCore.QSize(941, 561))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-image: url(njia_n6dh_161216.jpg));")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(-180, -20, 921, 551))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setGeometry(QtCore.QRect(90, 160, 811, 20))
        self.line.setStyleSheet("border-color: rgb(121, 157, 255);")
