### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Uuserui1)
add_subdirectory(Uuserui1Content)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	Uuserui1plugin
	Uuserui1Contentplugin)